#!/usr/bin/env bash
# .claude/hooks/log-session.sh
#
# Stop hook: writes a readable per-session log into the repo so that the prompts
# and Claude's reasoning behind a change travel with the PR, not just the diff.
#
# Best-effort by design: it must NEVER block or fail a session, so every path
# exits 0 and failures degrade gracefully.
#
# Output: dev/sessions/<date>-<short-session-id>.md  (git-tracked, R-build-ignored)

set -uo pipefail

# The hook payload arrives as JSON on stdin.
payload="$(cat)"

# jq is required for parsing; if it's not installed, exit quietly.
command -v jq >/dev/null 2>&1 || exit 0

transcript_path="$(printf '%s' "$payload" | jq -r '.transcript_path // empty')"
session_id="$(printf '%s' "$payload" | jq -r '.session_id // empty')"
# Prefer the project dir Claude Code exports; fall back to cwd from the payload.
project_dir="${CLAUDE_PROJECT_DIR:-$(printf '%s' "$payload" | jq -r '.cwd // empty')}"

# Nothing to do without a real transcript and a place to write it.
[ -n "$transcript_path" ] && [ -f "$transcript_path" ] || exit 0
[ -n "$project_dir" ] || exit 0

out_dir="$project_dir/dev/sessions"
mkdir -p "$out_dir" 2>/dev/null || exit 0

short_id="${session_id:0:8}"
date_str="$(date +%Y-%m-%d)"
out_file="$out_dir/${date_str}-${short_id:-session}.md"

branch="$(git -C "$project_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"

# Header. Overwrites on each Stop for this session so the file stays current
# if the session is resumed and stopped again.
{
  echo "# Claude Code session log"
  echo
  echo "- Session: \`${session_id:-unknown}\`"
  echo "- Branch: \`${branch}\`"
  echo "- Ended: $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo
  echo "> Auto-generated by the Stop hook. User prompts and Claude's text"
  echo "> responses only; tool calls and file diffs are omitted (the PR diff"
  echo "> already shows those)."
  echo
} > "$out_file"

# Render user prompts and assistant text from the JSONL transcript.
#
# NOTE: the transcript schema is internal to Claude Code and can change between
# releases. If a future update breaks this extraction, adjust the jq filter
# below (or switch to `/export`). It is written defensively and skips anything
# it can't read rather than erroring.
if ! jq -r '
  select(.type == "user" or .type == "assistant")
  | (.message.role // .type) as $role
  | (
      if   (.message.content | type) == "string" then .message.content
      elif (.message.content | type) == "array"  then
        ([.message.content[] | select(.type == "text") | .text] | join("\n"))
      else empty end
    ) as $text
  | select($text != null and ($text | gsub("\\s"; "")) != "")
  | "## \($role)\n\n\($text)\n"
' "$transcript_path" >> "$out_file" 2>/dev/null; then
  # Parsing failed (likely a schema change) — keep the raw transcript so the
  # record is not lost, and note it in the log.
  echo "_(Could not parse transcript into Markdown; raw JSONL copied alongside.)_" >> "$out_file"
  cp "$transcript_path" "$out_dir/${date_str}-${short_id:-session}.jsonl" 2>/dev/null || true
fi

exit 0
