#!/usr/bin/env bash
# .claude/hooks/log-session.sh
#
# Stop hook: writes a readable log of the session into the repo so that the
# prompts and Claude's reasoning behind a change travel with the PR, not just the
# diff.
#
# One log file per (session, branch). The hook fires at the end of every turn;
# it appends only the turns produced since it last ran to the file for whichever
# branch is currently checked out. Work done on a feature branch therefore lands
# in that branch's file, and a session that moves between branches produces one
# file per branch rather than a single interleaved log. (Resolves the branch and
# one-session-many-PRs problems recorded in issue #37.)
#
# Best-effort by design: it must NEVER block or fail a session, so every path
# exits 0 and failures degrade gracefully.
#
# Output:  dev/sessions/<start-date>-<short-session-id>-<branch>.md
#          (git-tracked, R-build-ignored)
# State:   <git-dir>/vci-session-logs/<session>.state   (never tracked)

set -uo pipefail

# The hook payload arrives as JSON on stdin.
payload="$(cat)"

# jq is required for parsing; if it's not installed, exit quietly.
command -v jq >/dev/null 2>&1 || exit 0

transcript_path="$(printf '%s' "$payload" | jq -r '.transcript_path // empty')"
session_id="$(printf '%s' "$payload" | jq -r '.session_id // empty')"
# Prefer the project dir Claude Code exports; fall back to cwd from the payload.
project_dir="${CLAUDE_PROJECT_DIR:-$(printf '%s' "$payload" | jq -r '.cwd // empty')}"

# Nothing to do without a real transcript and a place to write it.
[ -n "$transcript_path" ] && [ -f "$transcript_path" ] || exit 0
[ -n "$project_dir" ] || exit 0

out_dir="$project_dir/dev/sessions"
mkdir -p "$out_dir" 2>/dev/null || exit 0

short_id="${session_id:0:8}"
[ -n "$short_id" ] || short_id="session"

# Current branch, sanitised for use in a filename ('/' and spaces -> '-').
branch="$(git -C "$project_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
[ -n "$branch" ] || branch="unknown"
branch_safe="$(printf '%s' "$branch" | tr '/ ' '--' | tr -cd '[:alnum:]._-')"
[ -n "$branch_safe" ] || branch_safe="unknown"

# Per-session state lives inside the git dir: always present in a repo, never
# tracked, and excluded from the built package for free. Fall back to a dotdir
# under dev/sessions/ if the git dir cannot be located.
git_dir="$(git -C "$project_dir" rev-parse --git-dir 2>/dev/null || true)"
if [ -n "$git_dir" ]; then
  case "$git_dir" in
    /*) state_dir="$git_dir/vci-session-logs" ;;
    *) state_dir="$project_dir/$git_dir/vci-session-logs" ;;
  esac
else
  state_dir="$out_dir/.state"
fi
mkdir -p "$state_dir" 2>/dev/null || exit 0

state_key="$(printf '%s' "${session_id:-$short_id}" | tr -cd '[:alnum:]._-')"
[ -n "$state_key" ] || state_key="session"
state_file="$state_dir/${state_key}.state"

# State is two lines: the raw transcript-line cursor, and the session start date.
cursor=0
start_date=""
if [ -f "$state_file" ]; then
  cursor="$(sed -n '1p' "$state_file" 2>/dev/null)"
  start_date="$(sed -n '2p' "$state_file" 2>/dev/null)"
fi
case "$cursor" in '' | *[!0-9]*) cursor=0 ;; esac
[ -n "$start_date" ] || start_date="$(date +%Y-%m-%d)"

out_file="$out_dir/${start_date}-${short_id}-${branch_safe}.md"

# How far the transcript now extends, in raw JSONL lines.
total="$(wc -l < "$transcript_path" 2>/dev/null | tr -d ' ')"
case "$total" in '' | *[!0-9]*) total=0 ;; esac

# Compaction guard: if the transcript is now shorter than our cursor, Claude Code
# has summarised and rewritten it. Earlier turns were already logged above, so
# re-baseline to the current end rather than re-dumping the summary.
if [ "$total" -lt "$cursor" ]; then
  [ -f "$out_file" ] && printf '\n_(Transcript compacted; earlier turns already logged above. Continuing.)_\n' >> "$out_file"
  cursor="$total"
fi

new_count=$((total - cursor))
if [ "$new_count" -gt 0 ]; then
  # Write the header once, when the branch's file is first created.
  if [ ! -f "$out_file" ]; then
    {
      echo "# Claude Code session log"
      echo
      echo "- Session: \`${session_id:-unknown}\`"
      echo "- Branch: \`${branch}\`"
      echo "- Started: ${start_date}"
      echo
      echo "> Auto-generated by the Stop hook, one file per branch. User prompts and"
      echo "> Claude's text responses only; tool calls and file diffs are omitted (the"
      echo "> PR diff already shows those). Appended to at the end of each turn."
      echo
    } > "$out_file"
  fi

  # Render only the new slice of the transcript (lines after the cursor).
  #
  # NOTE: the transcript schema is internal to Claude Code and can change between
  # releases. If a future update breaks this extraction, adjust the jq filter
  # below (or switch to `/export`). It is written defensively and, on failure,
  # keeps the raw slice rather than losing the record.
  if ! tail -n +"$((cursor + 1))" "$transcript_path" 2>/dev/null | jq -r '
      select(.type == "user" or .type == "assistant")
      | (.message.role // .type) as $role
      | (
          if   (.message.content | type) == "string" then .message.content
          elif (.message.content | type) == "array"  then
            ([.message.content[] | select(.type == "text") | .text] | join("\n"))
          else empty end
        ) as $text
      | select($text != null and ($text | gsub("\\s"; "")) != "")
      | "## \($role)\n\n\($text)\n"
    ' >> "$out_file" 2>/dev/null; then
    printf '\n_(Could not parse part of the transcript into Markdown; raw JSONL copied alongside.)_\n' >> "$out_file"
    tail -n +"$((cursor + 1))" "$transcript_path" >> "${out_file%.md}.jsonl" 2>/dev/null || true
  fi
fi

# Advance the cursor to the current end and persist the start date.
{
  echo "$total"
  echo "$start_date"
} > "$state_file" 2>/dev/null || true

exit 0
